version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mkulimalink-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: mkulimalink-redis-dev
    ports:
      - "6379:6379"

volumes:
  mongo-dev-data:
